version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - LOCAL_MODEL_ENDPOINT=${LOCAL_MODEL_ENDPOINT}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ANTHROPIC_API_URL=${ANTHROPIC_API_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_URL=${OPENAI_API_URL}

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
