name: Build Docker Images

on:
  push:
    branches:
      - "main"

jobs:
  prepare_tag:
    outputs:
      tag: ${{ steps.semver.outputs.next }}
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          patchAll: true

      - name: Push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.semver.outputs.next }}
          tag_prefix: ""

  build_and_push:
    needs: prepare_tag
    permissions:
      contents: write
      packages: write

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - image: ghcr.io/mischavandenburg/sb-llm-demo-frontend
            dockerfile: llm-demo/frontend/Dockerfile
            path: llm-demo/frontend
          - image: ghcr.io/mischavandenburg/sb-llm-demo-backend
            dockerfile: llm-demo/backend/Dockerfile
            path: llm-demo/backend
          - image: ghcr.io/mischavandenburg/sb-llm-demo-llm
            dockerfile: llm-demo/llm/Dockerfile
            path: llm-demo/llm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.path }}
          platforms: linux/amd64
          tags: ${{ matrix.image }}:${{ needs.prepare_tag.outputs.tag }}
          file: ${{ matrix.dockerfile }}
          push: true

  update_gitops:
    # if: false  # Temporarily disabled
    needs:
      - prepare_tag
      - build_and_push
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitOps repository
        uses: actions/checkout@v4
        with:
          repository: mischavandenburg/splitbrain-demo-gitops
          ref: main
          token: "${{ secrets.GITOPS_PAT }}"

      - name: Update Image Tags
        uses: mikefarah/yq@master
        with:
          cmd: |
            # Update frontend deployment
            yq e '.spec.template.spec.containers[0].image = "ghcr.io/mischavandenburg/sb-llm-demo-frontend:${{ needs.prepare_tag.outputs.tag }}"' -i ./apps/frontend/deployment.yaml
            
            # Update backend deployment
            yq e '.spec.template.spec.containers[0].image = "ghcr.io/mischavandenburg/sb-llm-demo-backend:${{ needs.prepare_tag.outputs.tag }}"' -i ./apps/backend/deployment.yaml
            
            # Update llm deployment
            yq e '.spec.template.spec.containers[0].image = "ghcr.io/mischavandenburg/sb-llm-demo-llm:${{ needs.prepare_tag.outputs.tag }}"' -i ./apps/llm/deployment.yaml

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Update deployments with tag ${{ needs.prepare_tag.outputs.tag }}"
